export const lugaresDeAlberti = [
  {
    url: "/salamone/municipalidad.jpg",
    slug: "municipalidad",
    titulo: "Palacio Municipal: La Torre que Vigila el Tiempo",
    descripcion:
      "El Palacio Municipal de Alberti, diseñado por el emblemático arquitecto Francisco Salamone, se alza como un faro de modernidad en medio de la pampa bonaerense. Su característica torre con reloj no solo marca el paso del tiempo, sino que simboliza la firmeza institucional de una época de transformación. Construido a fines de la década del 30, este edificio es una obra maestra del Art Decó con elementos futuristas, y uno de los exponentes más representativos del legado salamónico. La estructura transmite una sensación de monumentalidad e innovación, con líneas limpias, simetría y detalles escultóricos únicos. Actualmente, sigue funcionando como sede administrativa del municipio y es un punto obligado para los visitantes interesados en la historia y la arquitectura. Su imagen se ha convertido en un ícono visual de Alberti, representando tanto el pasado como la proyección hacia el futuro del pueblo. Caminar por sus alrededores es retroceder en el tiempo y reencontrarse con una Argentina que apostaba a lo grandioso incluso en sus pequeñas ciudades.",
  },
  {
    url: "/salamone/parque.jpg",
    slug: "parque",
    titulo: "Parque Municipal: Naturaleza en el Corazón del Pueblo",
    descripcion:
      "El Parque Municipal de Alberti es un pulmón verde que combina naturaleza, esparcimiento y memoria local. Este espacio amplio, adornado con árboles añejos y caminos serpenteantes, es el lugar de encuentro para generaciones enteras de albertinos. Construido en las primeras décadas del siglo XX, el parque ha evolucionado con el tiempo sin perder su esencia: ser un refugio de tranquilidad. Aquí, niños corren por sus senderos, familias se reúnen para los clásicos picnics y los adultos mayores encuentran un espacio para caminar o descansar bajo la sombra generosa. Su cercanía al casco urbano lo convierte en una extensión del ritmo cotidiano del pueblo. Además, en fechas patrias o festividades locales, el parque cobra vida con ferias, recitales y celebraciones comunitarias. En su interior también se encuentran monumentos que rinden homenaje a personalidades destacadas y momentos claves de la historia albertina. El Parque Municipal es mucho más que un espacio verde: es el alma pública de Alberti, donde el pasado y el presente se dan la mano bajo el cielo abierto.",
  },
  {
    url: "/museos/vaccarezza.jpg",
    slug: "vaccarezza",
    titulo: "Casa Andrés Vaccarezza: Un Refugio de Historia y Cultura",
    descripcion:
      "La Casa de Andrés Vaccarezza, hoy convertida en espacio cultural, representa un capítulo esencial en la historia de Alberti. Esta vivienda, construida en los albores del siglo XX, perteneció a una de las familias más influyentes del pueblo. Andrés Vaccarezza, figura destacada en la política y el desarrollo local, dejó una huella imborrable que va más allá de su nombre asociado a la estación de ferrocarril. La casona, de arquitectura sobria y elegante, conserva elementos originales como sus pisos de madera, ventanales de hierro forjado y techos altos, que transportan al visitante a otra época. En la actualidad, la casa funciona como un centro cultural donde se dictan talleres, se realizan exposiciones artísticas y eventos que celebran la identidad albertina. Es común ver muestras de artistas locales y regionales, fomentando el diálogo entre generaciones a través del arte. También sirve como sede para reuniones vecinales y proyectos comunitarios. Visitarla no solo implica recorrer un espacio físico, sino también sumergirse en la rica trama de historias que tejieron el Alberti de ayer y siguen inspirando el de hoy. Es un símbolo de la preservación del patrimonio y la apuesta al futuro desde la memoria.",
  },
  {
    url: "/museos/iglesia.jpg",
    slug: "parroquia",
    titulo: "Parroquia San José: Fe y Testimonio a Través de los Años",
    descripcion:
      "La Parroquia San José se alza en el corazón de Alberti como un faro espiritual y arquitectónico. Su construcción comenzó en las primeras décadas del siglo XX y desde entonces ha sido testigo y protagonista de los momentos más importantes del pueblo: bautismos, casamientos, despedidas y celebraciones patronales. Su fachada sobria, de líneas clásicas, esconde un interior cálido, adornado con vitrales coloridos, altares de madera tallada y una atmósfera de recogimiento. El templo ha sido un punto de encuentro para la comunidad católica de Alberti y un espacio de contención espiritual en tiempos de alegría y dificultad. Su campanario, que marca las horas y convoca a la misa, forma parte del paisaje sonoro habitual del pueblo. Cada 19 de marzo, día de San José, la parroquia cobra vida con procesiones y misas especiales. A lo largo del tiempo, el edificio ha recibido restauraciones que respetan su esencia original. Hoy sigue en plena actividad, ofreciendo no solo servicios religiosos sino también apoyo social, formación y actividades para jóvenes. Visitar la Parroquia San José es adentrarse en el corazón espiritual de Alberti y comprender la profunda fe que caracteriza a su gente.",
  },
  {
    url: "/museos/hospital.jpg",
    slug: "hospital",
    titulo: "Hospital Municipal: Tradición de Servicio y Compromiso Humano",
    descripcion:
      "El Hospital Municipal de Alberti ha sido, desde sus inicios, un pilar fundamental para la salud y el bienestar de la comunidad. Fundado en el siglo XX con un fuerte sentido de solidaridad y atención pública, este centro de salud ha crecido con el pueblo, adaptándose a las nuevas tecnologías médicas sin perder el trato humano que lo caracteriza. Su arquitectura funcional esconde historias de nacimientos, recuperaciones y también de lucha en momentos difíciles. Médicos, enfermeras y trabajadores de la salud han sido figuras centrales en la vida cotidiana de los albertinos, especialmente en tiempos de crisis como la pandemia. El hospital no solo ofrece servicios de guardia y especialidades médicas, sino que también actúa como centro de prevención, campañas sanitarias y educación en salud. Además, se destaca por su vínculo cercano con la comunidad, siendo frecuentemente parte de actividades interinstitucionales. Su compromiso con la salud pública lo convierte en un símbolo de cuidado y pertenencia. Hoy, renovado en muchas de sus áreas, el Hospital Municipal sigue firme en su misión de brindar atención médica accesible, con calidez y profesionalismo, para todas las generaciones del pueblo.",
  },
  {
    url: "/salamone/secundaria.jpg",
    slug: "secundaria",
    titulo: "Escuela N°2: Semillero de Generaciones Albertinas",
    descripcion:
      "La Escuela Primaria N°2 'Domingo Faustino Sarmiento' es una de las instituciones educativas más emblemáticas de Alberti. Fundada en los albores del siglo XX, su edificio de estilo tradicional ha sido testigo del paso de miles de estudiantes que hoy integran el tejido social y profesional del pueblo. Con sus aulas amplias, galerías abiertas y el característico mástil en el patio central, la escuela mantiene ese espíritu de comunidad donde el aprendizaje va de la mano de la contención. Más allá del aula, la institución impulsa ferias científicas, actividades culturales y propuestas deportivas que enriquecen la formación de sus alumnos. Muchos de los actuales referentes locales —desde médicos hasta comerciantes— dieron sus primeros pasos académicos en sus aulas. En fechas patrias, la escuela se viste de fiesta con actos llenos de tradición y participación. Su cuerpo docente, comprometido y vocacional, ha sido clave en mantener la excelencia y el prestigio educativo a lo largo del tiempo. Hoy, la Escuela N°2 no solo forma a los futuros ciudadanos de Alberti, sino que también continúa siendo un símbolo de igualdad de oportunidades, acceso a la educación y crecimiento colectivo.",
  },
  {
    url: "/salamone/monumento.jpg",
    slug: "plaza",
    titulo: "Plaza Arias: El Corazón Cívico de Alberti",
    descripcion:
      "La Plaza Arias es el epicentro social y cívico de Alberti, donde se cruzan la historia, la vida cotidiana y la identidad del pueblo. Rodeada por los edificios más importantes —la municipalidad, la parroquia, la comisaría y comercios tradicionales—, esta plaza ha sido, desde siempre, el punto de encuentro natural para generaciones de albertinos. Su nombre honra a uno de los benefactores locales, y sus caminos arbolados invitan a caminar sin apuro, disfrutar del aire libre o simplemente observar el movimiento diario. Las palmeras altas, bancos antiguos y faroles coloniales le otorgan un encanto particular. Aquí se celebran los actos patrios, los carnavales, ferias artesanales y espectáculos que llenan de vida cada rincón. En el centro de la plaza se encuentra el tradicional mástil, símbolo de unidad y pertenencia. Por las tardes, se vuelve un lugar familiar, donde niños juegan y adultos disfrutan del descanso. Plaza Arias no es solo un espacio público, es una extensión de la identidad albertina, una postal viva donde la historia y el presente se entrelazan en cada paso.",
  },
  {
    url: "/salamone/cementerio.jpg",
    slug: "cementerio",
    titulo: "Cementerio de Alberti: Silencio, Arte y Memoria",
    descripcion:
      "El Cementerio Municipal de Alberti es una joya silenciosa que conjuga arquitectura, historia y homenaje. Diseñado en parte por Francisco Salamone, su ingreso monumental con portones de hierro y líneas geométricas representa un enfoque singular del arte funerario. El arco de entrada, de concreto macizo y estilo racionalista, se impone con una sobriedad que invita al respeto. Dentro del predio, se hallan mausoleos, esculturas y lápidas que narran la vida de familias fundadoras, antiguos intendentes, docentes, trabajadores y vecinos que dejaron su huella. Caminar por sus senderos es transitar por la historia íntima del pueblo, donde cada tumba guarda una memoria viva. Además, muchas de sus obras escultóricas fueron realizadas por artistas locales, convirtiendo al cementerio en un pequeño museo a cielo abierto. Con el paso de los años, el lugar ha sido objeto de restauraciones que respetan su valor patrimonial. En fechas especiales, como el Día de Todos los Santos, el cementerio cobra una nueva vida con visitas guiadas, música y velas, honrando a los que ya no están. Es un espacio donde la muerte no representa un final, sino una continuidad simbólica con el legado de Alberti.",
  },
  {
    url: "/museos/raul_lozza.jpg",
    slug: "museo",
    titulo: "Museo 'Raúl Lozza': Color, Vanguardia y Pasión Local",
    descripcion:
      "El Museo 'Raúl Lozza' de Alberti rinde homenaje a uno de los artistas más vanguardistas del arte argentino del siglo XX. Raúl Lozza, nacido en este pueblo en 1911, fue pionero del arte perceptista y desarrolló una obra plástica reconocida internacionalmente. El museo, ubicado en una antigua casa restaurada, no solo exhibe piezas originales del artista, sino que también funciona como centro de interpretación y difusión de su pensamiento estético. En sus salas se pueden ver obras que exploran la abstracción geométrica, los colores puros y la relación entre forma y espacio. Además, ofrece talleres, charlas y actividades educativas que acercan a nuevas generaciones al legado artístico local. La institución cumple un rol vital en la cultura de Alberti, generando orgullo e identidad entre los vecinos. La figura de Lozza trasciende las fronteras del arte: representa el potencial creativo de un pueblo que nunca renunció a sus raíces. Cada visita al museo es una experiencia sensorial y reflexiva, donde el arte se convierte en puente entre lo local y lo universal. Alberti vibra con su color.",
  },
  {
    url: "/photos/9.jpg",
    slug: "estación",
    titulo: "Estación Andrés Vaccarezza: La Puerta del Progreso",
    descripcion:
      "La estación de ferrocarril Andrés Vaccarezza es uno de los símbolos históricos de Alberti, tanto por su valor arquitectónico como por su importancia en el desarrollo del pueblo. Inaugurada a principios del siglo XX, fue un nodo vital en la expansión agrícola y comercial de la región. Su edificio, de líneas sobrias y techos a dos aguas, conserva el encanto de las estaciones ferroviarias clásicas de Argentina. Durante décadas, fue testigo del ir y venir de familias, comerciantes y trabajadores que tejieron la vida albertina. El tren no solo traía productos y pasajeros, sino también noticias y sueños. Con la reducción de los servicios ferroviarios, la estación fue perdiendo protagonismo, pero no identidad. Hoy, aún se conserva como patrimonio y algunos trenes de carga y ocasionales servicios especiales la mantienen viva. Su entorno se ha transformado en un espacio para ferias, exposiciones y actividades culturales. La estación es un símbolo de tránsito, de memoria y de esperanza. Representa una época donde el tren era el lazo directo entre Alberti y el resto del país, y hoy sigue siendo un emblema del espíritu ferroviario que marcó a fuego la historia local.",
  },
];

export const galleryImages = [
  "/0.jpg",
  "/1.jpeg",
  "/2.jpg",
  "/3.jpg",
  "/4.jpg",
  "/5.jpg",
  "/6.jpg",
  "/7.png",
  "/8.jpeg",
  "/9.jpg",
  "/10.jpg",
  "/11.jpeg",
  "/12.jpeg",
  "/13.jpeg",
  "/14.jpg",
  "/15.jpg",
  "/16.jpg",
  "/17.jpeg",
  "/18.jpeg",
  "/19.jpg",
  "/20.jpeg",
  "/21.jpeg",
  "/22.jpeg",
  "/23.jpeg",
  "/24.jpg",
  "/25.jpg",
  "/26.jpg",
  "/27.jpg",
  "/28.jpeg",
  "/29.jpeg",
  "/30.jpeg",
  "/31.jpeg",
  "/32.jpeg",
  "/33.jpg",
  "/34.jpg",
  "/35.jpeg",
  "/37.jpg",
  "/38.jpg",
  "/39.jpg",
  "/40.jpg",
  "/41.jpg",
  "/42.jpg",
  "/43.jpg",
  "/44.jpg",
  "/45.jpg",
  "/46.jpg",
  "/47.jpg",
  "/48.jpg",
  "/49.jpg",
  "/50.jpg",
  "/51.jpg",
  "/52.jpg",
  "/53.jpg",
  "/54.jpg",
  "/55.jpg",
  "/56.jpg",
  "/57.jpg",
  "/58.jpg",
  "/59.jpg",
  "/60.jpg",
  "/61.jpg",
  "/62.jpg",
  "/63.jpg",
  "/64.jpg",
];
